theme: jekyll-theme-minimal

name: Tiani's BGGN 213 Course work

description: This page contains documentation that proves that I was indeed paying attention in class

image: https://bioboot.github.io/bggn213_S19/assets/img/logo.png
