theme: jekyll-theme-minimal

title: Introduction to Bioinformatics 

description: This page contains documentation that proves that I was indeed paying attention in class

logo: https://bioboot.github.io/bggn213_S19/assets/img/logo.png
